/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.tesa.ticket.views.developboss;

/**
 *
 * @author vaselinux
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setExtendedState(MainView.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        solicitudMenu = new javax.swing.JMenu();
        solicitudMenuItem = new javax.swing.JMenuItem();
        casosMenu1 = new javax.swing.JMenu();
        activosMenuItem1 = new javax.swing.JMenuItem();
        rachazadosMenuItem2 = new javax.swing.JMenuItem();
        desarrolloMenuItem3 = new javax.swing.JMenuItem();
        cerradoMenuItem4 = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        solicitudMenu.setMnemonic('m');
        solicitudMenu.setText("Menu");

        solicitudMenuItem.setMnemonic('s');
        solicitudMenuItem.setText("Solicitudes");
        solicitudMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudMenuItemActionPerformed(evt);
            }
        });
        solicitudMenu.add(solicitudMenuItem);

        casosMenu1.setText("Casos");

        activosMenuItem1.setMnemonic('a');
        activosMenuItem1.setText("Activos");
        casosMenu1.add(activosMenuItem1);

        rachazadosMenuItem2.setMnemonic('r');
        rachazadosMenuItem2.setText("Rechazados");
        casosMenu1.add(rachazadosMenuItem2);

        desarrolloMenuItem3.setMnemonic('e');
        desarrolloMenuItem3.setText("En_Desarrollo");
        casosMenu1.add(desarrolloMenuItem3);

        cerradoMenuItem4.setMnemonic('c');
        cerradoMenuItem4.setText("Cerrados");
        casosMenu1.add(cerradoMenuItem4);

        solicitudMenu.add(casosMenu1);

        salirMenuItem.setMnemonic('a');
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        solicitudMenu.add(salirMenuItem);

        menuBar.add(solicitudMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void solicitudMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudMenuItemActionPerformed
        // TODO add your handling code here:
        if(Solicitudes.bandera==0){
        
                Solicitudes sol = new Solicitudes();
                //sol.setVisible(true);
                this.add(sol);
                desktopPane.add(sol);
                sol.setResizable(true);
                sol.setClosable(true);
                sol.show();
                Solicitudes.bandera=1;
            }
    }//GEN-LAST:event_solicitudMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem activosMenuItem1;
    private javax.swing.JMenu casosMenu1;
    private javax.swing.JMenuItem cerradoMenuItem4;
    private javax.swing.JMenuItem desarrolloMenuItem3;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem rachazadosMenuItem2;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JMenu solicitudMenu;
    private javax.swing.JMenuItem solicitudMenuItem;
    // End of variables declaration//GEN-END:variables

}
