/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.tesa.ticket.views;
import sv.com.tesa.ticket.controllers.CasesController;
import javax.swing.table.DefaultTableModel;
import sv.com.tesa.ticket.beans.LoginBean;
import javax.swing.JOptionPane;
import sv.com.tesa.ticket.beans.SingleCaseBean;
/**
 *
 * @author Reyes Alexander
 */
public class CasesView extends javax.swing.JInternalFrame {
   private CasesController ctrlCase;
    private SingleCaseBean beanCase;
    private LoginBean usuario;
    public static boolean isOpen = false;
    public static boolean sera = false;
    /**
     * Creates new form CasesView
     */
    public CasesView() {
        initComponents();
        ctrlCase = new CasesController();
        beanCase = new SingleCaseBean();
        cargarTabla();
    }
    
    private void cargarTabla(){
        try{
            TableCases.setModel(ctrlCase.listarCases().getModel());
            TableCases.getColumnModel().getColumn(0).setMinWidth(5);
            TableCases.getColumnModel().getColumn(0).setPreferredWidth(6);
        }catch(Exception ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CasesView().setVisible(true);
        });
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableCases = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        TableCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableCases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCases);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(367, 367, 367))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableCasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCasesMouseClicked
        DefaultTableModel dtm = (DefaultTableModel)TableCases.getModel();
        int fila = TableCases.getSelectedRow();
        beanCase.setId(dtm.getValueAt(fila, 0).toString());
        SingleCaseBean peticionIndividual = ctrlCase.listarCase(beanCase);
        if(!peticionIndividual.getId().equals("")){
            JOptionPane.showMessageDialog(null, "entre al if");
                CaseView vistaUnaPeticion = new CaseView(peticionIndividual);
                vistaUnaPeticion.setVisible(true);
        }        
    }//GEN-LAST:event_TableCasesMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       this.hide();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCases;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
