/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.tesa.ticket.views;
import java.util.HashMap;
import javax.swing.JOptionPane;
import sv.com.tesa.ticket.utils.Utilidades;
import sv.com.tesa.ticket.controllers.CasesController;
import sv.com.tesa.ticket.beans.CaseBean;
import sv.com.tesa.ticket.beans.LoginBean;
import sv.com.tesa.ticket.beans.RequestBean;
import sv.com.tesa.ticket.utils.Validaciones;
/**
 *
 * @author Edu
 */
public class NewCaseView extends javax.swing.JDialog {

    private CasesController ctrlCasos;
    private HashMap<Integer,String> mapEmpleados;
    private CaseBean caso;
    private RequestBean peticion;
    private RequestsView padre;
    /**
     * Creates new form NewCaseView
     */
    public NewCaseView(RequestBean peticion, RequestsView padre) {
        initComponents();
        this.padre = padre;
        this.setModal(true);
        agregarPaneFecha();
        ctrlCasos = new CasesController();
        mapEmpleados = ctrlCasos.listarEmpleadosACargo();
        this.peticion = peticion;
        llenarCbBoxEmpleados();
        txtTitulo.setText(peticion.getTitle());
    }
    
    private void agregarPaneFecha()
    {
        paneDate.add(Utilidades.opcionFecha()); 
    }
    
    private void llenarCbBoxEmpleados()
    {
        cbBoxEmpleados.removeAllItems();
        for (Integer id : mapEmpleados.keySet()) 
        {
            cbBoxEmpleados.addItem(mapEmpleados.get(id));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnCrearCaso = new javax.swing.JButton();
        cbBoxEmpleados = new javax.swing.JComboBox<>();
        paneDate = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Titulo de la solicitud:");

        jLabel2.setText("Fecha limite de entrega:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Asignado a:");

        txtTitulo.setEditable(false);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        btnCrearCaso.setText("Crear Caso");
        btnCrearCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCasoActionPerformed(evt);
            }
        });

        cbBoxEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        paneDate.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbBoxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnCrearCaso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addComponent(paneDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbBoxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearCaso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCasoActionPerformed
        // TODO add your handling code here:
        if (!txtDescripcion.getText().equals("")) {
            caso = new CaseBean();
            caso.setId(Utilidades.generarNumAleatorio());
            caso.setDepartamento(LoginBean.getDepartamento());
            caso.setIdSolicitud(peticion.getId());
            for (Integer id : mapEmpleados.keySet()) 
            {
                if (mapEmpleados.get(id).equals(cbBoxEmpleados.getSelectedItem())) {
                    caso.setEmpleadoAsignado(id);
                }
            }
            caso.setFechaLimite(Utilidades.regresarFecha());
            caso.setDescripcion(txtDescripcion.getText());
            System.out.println("Es fecha futura: " + Validaciones.esfechaFutura(caso.getFechaLimite()));

            if (Validaciones.esfechaFutura(caso.getFechaLimite())) {

                 boolean res = ctrlCasos.ingresarEmpledado(caso);
                 if (res) 
                {
                    JOptionPane.showMessageDialog(this, "Nuevo caso creado","Exito",
                            JOptionPane.INFORMATION_MESSAGE);
                    padre.cargarTabla();
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Hubo un error creando la peticion","Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "La fecha es limite se encuentra en el pasado o no "
                        + "ha selecionado una fecha","Error",
                            JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "La descripcion no puede ser vacia","Error",
                            JOptionPane.ERROR_MESSAGE);
        }
        
        

    }//GEN-LAST:event_btnCrearCasoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCaso;
    private javax.swing.JComboBox<String> cbBoxEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneDate;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
