/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.tesa.ticket.views;

import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.com.tesa.ticket.beans.LoginBean;
import sv.com.tesa.ticket.beans.RequestBean;
import sv.com.tesa.ticket.beans.SingleRequestBean;
import sv.com.tesa.ticket.controllers.RequestController;

/**
 *
 * @author Edu
 */
public class RequestsView extends javax.swing.JInternalFrame{

    private RequestController ctrlPeticiones;
    private LoginBean usuario;
    private RequestBean peticion;
    private HashMap<Integer,String> departamentos;

    
    public RequestsView(LoginBean logUser) {
        initComponents();
        usuario = logUser;
        ctrlPeticiones = new RequestController();
        departamentos = ctrlPeticiones.listarTiposPeticion();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeticiones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tablaPeticiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Titulo", "Descripcion", "Departamento", "Tipo de peticion", "Estado de la peticion"
            }
        ));
        tablaPeticiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPeticionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPeticiones);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Peticiones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(348, 348, 348))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPeticionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPeticionesMouseClicked
        // TODO add your handling code here:
        peticion = new RequestBean();
        DefaultTableModel dtm = (DefaultTableModel)tablaPeticiones.getModel();
        int indexFila = tablaPeticiones.getSelectedRow();
        peticion.setId(Integer.parseInt(dtm.getValueAt(indexFila, 0).toString()));
        peticion.setCreatedBy(usuario.getId());
        SingleRequestBean peticionIndividual = ctrlPeticiones.listarPeticionIndividual(peticion);
        if (peticionIndividual.getId() != 0) 
        {
            boolean res = "Solicitud rechazada".equals(peticionIndividual.getEstado());
            if (res) {
                RequestView vistaUnaPeticion = new RequestView(peticionIndividual, this);
                this.getParent().add(vistaUnaPeticion);
                vistaUnaPeticion.show();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Solo se pueden modificar peticiones "
                        + "que esten rechazados","Alerta",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No puedes modificar esta solicitud "
                    + "porque no fue creada por este usuario","Alerta",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tablaPeticionesMouseClicked

    protected void cargarTabla()
    {
        try {
            tablaPeticiones.setModel(ctrlPeticiones.listarPeticiones(usuario).getModel());
        } catch (Exception e) {
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPeticiones;
    // End of variables declaration//GEN-END:variables
}
