/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.tesa.ticket.views;
import java.util.HashMap;
import javax.swing.JOptionPane;
import sv.com.tesa.ticket.beans.SingleRequestBean;
import sv.com.tesa.ticket.beans.RequestBean;
import sv.com.tesa.ticket.controllers.RequestController;
/**
 *
 * @author Edu
 */
public class RequestView extends javax.swing.JInternalFrame {

    private SingleRequestBean peticionIndividual;
    private RequestController ctrlPeticion;
    private RequestsView padre;
    private HashMap<Integer,String> mapTipoPeticion;
    
    /**
     * Creates new form RequestView
     * @param peticion
     * @param padre
     */
    public RequestView(SingleRequestBean peticion, RequestsView padre) {
        initComponents();
        ctrlPeticion = new RequestController();
        this.padre = padre;
        this.peticionIndividual = peticion;
        mapTipoPeticion = ctrlPeticion.listarTiposPeticion();
        llenarCampos();
    }

    
    private void llenarCampos()
    {
        
        if (peticionIndividual != null) 
        {
            txtId.setText(String.valueOf(peticionIndividual.getId()));
            cbBoxTipoSolicitud.removeAllItems();
            cbBoxTipoSolicitud.addItem(peticionIndividual.getTipoPeticion());
            txtDepartamento.setText(peticionIndividual.getDepartamento());
            txtTitulo.setText(peticionIndividual.getTitulo());
            txtDescripcion.setText(peticionIndividual.getDescripcion());
            txtCreadoPor.setText(peticionIndividual.getCreadoPor());
            txtEstadoSolicitud.setText(peticionIndividual.getEstado());
            txtComentario.setText(peticionIndividual.getComentario());
            txtFechaCreacion.setText(peticionIndividual.getFechaCreacion());
            txtFechaModificacion.setText(peticionIndividual.getFechaModificacion());
            
        }
    }
    
    private void carbarCbBoxTipoPeticion()
    {
        cbBoxTipoSolicitud.removeAllItems();
        for (Integer id : mapTipoPeticion.keySet()) {
            cbBoxTipoSolicitud.addItem(mapTipoPeticion.get(id));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtCreadoPor = new javax.swing.JTextField();
        txtEstadoSolicitud = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        txtFechaCreacion = new javax.swing.JTextField();
        txtFechaModificacion = new javax.swing.JTextField();
        rdBtnModificar = new javax.swing.JRadioButton();
        rdBtnEliminar = new javax.swing.JRadioButton();
        btnGuardarCambios = new javax.swing.JButton();
        cbBoxTipoSolicitud = new javax.swing.JComboBox<>();

        jLabel1.setText("Id solicitud:");

        txtId.setEditable(false);

        jLabel2.setText("Tipo de Solicitud:");

        jLabel3.setText("Departamento Solicitante:");

        jLabel4.setText("Titulo: ");

        jLabel5.setText("Descripcion:");

        jLabel6.setText("Credo por:");

        jLabel7.setText("Estado de la Solicitud:");

        jLabel8.setText("Comentario:");

        jLabel9.setText("Fecha de creacion:");

        jLabel10.setText("Fecha de ultima modificacion:");

        txtDepartamento.setEditable(false);

        txtTitulo.setEditable(false);

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescripcion);

        txtCreadoPor.setEditable(false);

        txtEstadoSolicitud.setEditable(false);

        txtComentario.setEditable(false);
        txtComentario.setColumns(20);
        txtComentario.setLineWrap(true);
        txtComentario.setRows(5);
        txtComentario.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtComentario);

        txtFechaCreacion.setEditable(false);

        txtFechaModificacion.setEditable(false);

        rdBtnModificar.setText("Modificar");
        rdBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnModificarActionPerformed(evt);
            }
        });

        rdBtnEliminar.setText("Eliminar");

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        cbBoxTipoSolicitud.setEditable(true);
        cbBoxTipoSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                        .addComponent(cbBoxTipoSolicitud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDepartamento)
                                        .addComponent(txtTitulo)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCreadoPor)
                                        .addComponent(txtEstadoSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFechaModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(txtFechaCreacion))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdBtnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdBtnEliminar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnGuardarCambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbBoxTipoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCreadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEstadoSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtFechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnModificar)
                    .addComponent(rdBtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarCambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        if (rdBtnModificar.isSelected()) 
        {
            RequestBean peticion = new RequestBean();
            peticion.setDescription(txtDescripcion.getText());
            peticion.setId(Integer.parseInt(txtId.getText()));
            for (Integer id : mapTipoPeticion.keySet()) {
                if(mapTipoPeticion.get(id).equals(cbBoxTipoSolicitud.getSelectedItem()))
                {
                    peticion.setRequestType(id);
                }
            }
            peticion.setTitle(txtTitulo.getText());
            peticion.setCommentary(null);
            boolean res = ctrlPeticion.modificarPeticion(peticion);
            
            if (res) {
                JOptionPane.showMessageDialog(this, "Datos modificados exitosamente","Resultado",
                    JOptionPane.INFORMATION_MESSAGE);
                padre.cargarTabla();
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al modificar los datos","Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            RequestBean peticion = new RequestBean();
            peticion.setId(Integer.parseInt(txtId.getText()));
            boolean res = ctrlPeticion.eliminarPeticion(peticion);
            if (res) {
                JOptionPane.showMessageDialog(this, "Datos eliminados exitosamente","Resultado",
                    JOptionPane.INFORMATION_MESSAGE);
                padre.cargarTabla();
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al eliminar los datos, "
                        + "tiene uno o mas casos asociados","Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void rdBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnModificarActionPerformed
        // TODO add your handling code here:
        if (rdBtnModificar.isSelected()) 
        {
            txtDescripcion.setEditable(true);
            txtTitulo.setEditable(true);
            carbarCbBoxTipoPeticion();
        }
    }//GEN-LAST:event_rdBtnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbBoxTipoSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdBtnEliminar;
    private javax.swing.JRadioButton rdBtnModificar;
    private javax.swing.JTextArea txtComentario;
    private javax.swing.JTextField txtCreadoPor;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEstadoSolicitud;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtFechaModificacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
