/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.tesa.ticket.views.admin;
import sv.com.tesa.ticket.beans.LoginBean;
/**
 *
 * @author Edu
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    AdminBossView vistaAdminJefes;
    AdminDeptView vistaJefesDept;
    
    public AdminView(LoginBean logUser) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        AdminMenu = new javax.swing.JMenu();
        adminDeptMenuItem = new javax.swing.JMenuItem();
        adminBossMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminMenu.setMnemonic('h');
        AdminMenu.setText("Administrar");

        adminDeptMenuItem.setMnemonic('c');
        adminDeptMenuItem.setText("Administrar Departamentos");
        adminDeptMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDeptMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(adminDeptMenuItem);

        adminBossMenuItem.setMnemonic('a');
        adminBossMenuItem.setText("Administrar Jefes");
        adminBossMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBossMenuItemActionPerformed(evt);
            }
        });
        AdminMenu.add(adminBossMenuItem);

        menuBar.add(AdminMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminDeptMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDeptMenuItemActionPerformed
        // TODO add your handling code here:
        vistaJefesDept = new AdminDeptView();
        desktopPane.add(vistaJefesDept);
        vistaJefesDept.show();
        
    }//GEN-LAST:event_adminDeptMenuItemActionPerformed

    private void adminBossMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBossMenuItemActionPerformed
        // TODO add your handling code here:
        vistaAdminJefes = new AdminBossView();
        desktopPane.add(vistaAdminJefes);
        vistaAdminJefes.show();
    }//GEN-LAST:event_adminBossMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem adminBossMenuItem;
    private javax.swing.JMenuItem adminDeptMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
