/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.com.tesa.ticket.views.admin;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sv.com.tesa.ticket.controllers.AdminBossController;
import sv.com.tesa.ticket.beans.EmployeeBean;
import sv.com.tesa.ticket.utils.Utilidades;
import sv.com.tesa.ticket.utils.Validaciones;
/**
 *
 * @author Edu
 */
public class AdminBossView extends javax.swing.JInternalFrame {

    private EmployeeBean beanEmp;
    private AdminBossController ctrlAdminJefe;
    private HashMap<Integer,String> mapRoles;
    private HashMap<String,String> mapDept;
    private HashMap<Integer,String> mapJefes;
    /**
     * Creates new form AdminBossViewInterno
     */
    public AdminBossView() {
        initComponents();
        ctrlAdminJefe = new AdminBossController();
        mapRoles = ctrlAdminJefe.listarRoles();
        mapDept = ctrlAdminJefe.listarDepartamentos();
        mapJefes = ctrlAdminJefe.listarJefes();
        cargarTabla();
        cargarCbBoxRol();
        cargarCbBoxDepartamentos();
        cargarCbBoxJefes();
        txtContraseña.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox3 = new javax.swing.JCheckBox();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        cbBoxRol = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJefesDept = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chbModPass = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        cbBoxDept = new javax.swing.JComboBox<>();
        cbBoxNuevoEmpleado = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cbBoxJefes = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Menu Administacion");

        jCheckBox3.setText("Jefes de Desarrolo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Correo:");

        btnModificar.setText("Modificar Empleado");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar Empleado");
        btnIngresar.setEnabled(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        cbBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Contraseña:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Departamento:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Informacion:");

        tablaJefesDept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre Empleado", "Correo Empleado", "Cargo", "Departamento"
            }
        ));
        tablaJefesDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJefesDeptMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaJefesDept);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre Empleado:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Id:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Apellido Empleado:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("* Este campo no es necesario cuando ingresa un nuevo Empleado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Rol:");

        buttonGroup1.add(chbModPass);
        chbModPass.setText("Modificar Empleado");
        chbModPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbModPassActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Registros:");

        jCheckBox1.setText("Jefes de Departamentos");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        cbBoxDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(cbBoxNuevoEmpleado);
        cbBoxNuevoEmpleado.setText("Ingresar nuevo empleado");
        cbBoxNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoxNuevoEmpleadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Jefe del empleado:");

        cbBoxJefes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbBoxJefes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApellido))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbBoxDept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbBoxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtContraseña)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chbModPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbBoxNuevoEmpleado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox3)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbBoxDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbBoxJefes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbModPass)
                    .addComponent(cbBoxNuevoEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            boolean op = chbModPass.isSelected();
            System.out.println(op);
            beanEmp = new EmployeeBean();
            beanEmp.setId(Integer.parseInt(txtIdEmpleado.getText()));
            beanEmp.setNombre(txtNombre.getText());
            beanEmp.setApellido(txtApellido.getText());
            beanEmp.setEmail(txtCorreo.getText());
            for (Integer id : mapRoles.keySet()) {
                if (mapRoles.get(id).equals(cbBoxRol.getSelectedItem()))
                {
                    beanEmp.setRol(id);
                }
            }
            beanEmp.setDepartamento(cbBoxDept.getSelectedItem().toString());
            beanEmp.setDepartamento((String) Utilidades.regresarValorHashMap(mapDept, cbBoxDept.getSelectedItem().toString()));
            beanEmp.setPassword(new String(txtContraseña.getPassword()));
            for (Integer id : mapJefes.keySet()) {
                if (mapJefes.get(id).equals(cbBoxJefes.getSelectedItem())) {
                    beanEmp.setJefe(id);
                }
            }
            if (Validaciones.esCorreoElectronico(beanEmp.getEmail())) {
                if (ctrlAdminJefe.modificarJefe(beanEmp, op))
                {
                    cargarTabla();
                    limpiarTexto();
                    JOptionPane.showMessageDialog(this, "Los datos del empleado han sido modificados exitosamente","Exito",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al modificar los datos","Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        try {
            beanEmp = new EmployeeBean();
            beanEmp.setNombre(txtNombre.getText());
            beanEmp.setApellido(txtApellido.getText());
            beanEmp.setEmail(txtCorreo.getText());
            for (Integer id : mapRoles.keySet()) {
                if (mapRoles.get(id).equals(cbBoxRol.getSelectedItem()))
                {
                    beanEmp.setRol(id);
                }
            }
            beanEmp.setDepartamento((String) Utilidades.regresarValorHashMap(mapDept, cbBoxDept.getSelectedItem().toString()));
            

            if (Validaciones.esCorreoElectronico(beanEmp.getEmail())) {
                if(ctrlAdminJefe.ingresarEmpleado(beanEmp))
                {
                    cargarTabla();
                    limpiarTexto();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error al modificar los datos","Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void tablaJefesDeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJefesDeptMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tablaJefesDept.getModel();
        int indexFila = tablaJefesDept.getSelectedRow();
        txtIdEmpleado.setText(dtm.getValueAt(indexFila, 0).toString());
        String[] nombre = dtm.getValueAt(indexFila, 1).toString().split(" ");
        txtNombre.setText(nombre[0]);
        txtApellido.setText(nombre[1]);
        txtCorreo.setText(dtm.getValueAt(indexFila, 2).toString());
    }//GEN-LAST:event_tablaJefesDeptMouseClicked

    private void chbModPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbModPassActionPerformed

        if (chbModPass.isSelected())
        {
            txtContraseña.setEnabled(true);
            cbBoxDept.setEnabled(true);
            cbBoxJefes.setEditable(true);
            cbBoxRol.setEditable(true);
            txtIdEmpleado.setEnabled(true);
            btnIngresar.setEnabled(false);
            btnModificar.setEnabled(true);
        }
        else
        {
            txtContraseña.setEnabled(false);
        }
    }//GEN-LAST:event_chbModPassActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cbBoxNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoxNuevoEmpleadoActionPerformed
        // TODO add your handling code here:
        if (cbBoxNuevoEmpleado.isSelected()) {
            txtIdEmpleado.setEnabled(false);
            txtContraseña.setEnabled(false);
            btnIngresar.setEnabled(true);
            btnModificar.setEnabled(false);
        }
        else
        {
            txtIdEmpleado.setEnabled(true);
        }
    }//GEN-LAST:event_cbBoxNuevoEmpleadoActionPerformed


    private void limpiarTexto()
    {
        txtIdEmpleado.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        cbBoxRol.setSelectedIndex(0);
        cbBoxDept.setSelectedIndex(0);
        txtContraseña.setText("");
    }
    private void cargarTabla()
    {
        try {
            tablaJefesDept.setModel(ctrlAdminJefe.listarUsuarios().getModel());
            tablaJefesDept.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaJefesDept.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaJefesDept.getColumnModel().getColumn(2).setPreferredWidth(20);
        } catch (Exception e) {
        }
    }
    
    private void cargarCbBoxRol()
    {
        cbBoxRol.removeAllItems();
        for (Integer id : mapRoles.keySet()) {
            cbBoxRol.addItem(mapRoles.get(id));
        }
    }
 
    private void cargarCbBoxDepartamentos()
    {
        cbBoxDept.removeAllItems();
        for (String id : mapDept.keySet()) {
            cbBoxDept.addItem(mapDept.get(id));
        }
    }
    
    private void cargarCbBoxJefes()
    {
        cbBoxJefes.removeAllItems();
        for (Integer id : mapJefes.keySet()) 
        {
            cbBoxJefes.addItem(mapJefes.get(id));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbBoxDept;
    private javax.swing.JComboBox<String> cbBoxJefes;
    private javax.swing.JCheckBox cbBoxNuevoEmpleado;
    private javax.swing.JComboBox<String> cbBoxRol;
    private javax.swing.JCheckBox chbModPass;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaJefesDept;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
